// Stub aspMain RSP microcode for Wave Race 64
// TODO: Generate proper recompiled microcode using RSPRecomp
// This stub allows the project to compile but audio RSP tasks
// will not produce correct output at runtime.

#include "librecomp/rsp.hpp"

// Stub implementation - returns Broke (success) without processing
// The actual aspMain should be generated by RSPRecomp from the ROM's
// audio microcode (aspMain text segment)
RspExitReason aspMain(uint8_t* rdram, uint32_t ucode_addr) {
    // Signal successful completion without actually processing
    // Audio will not work correctly with this stub
    return RspExitReason::Broke;
}
