#!/usr/bin/env python3
"""
Extract function boundaries from N64 ROM using spimdisasm
and generate N64Recomp-compatible symbols.toml
"""

import spimdisasm
from spimdisasm import common as spimdisasm_common
from pathlib import Path
import struct

def read_rom(rom_path: str) -> bytes:
    """Read ROM file"""
    with open(rom_path, 'rb') as f:
        return f.read()

def detect_functions(rom_data: bytes, code_start_rom: int, code_end_rom: int, vram_start: int):
    """Detect function boundaries by analyzing JAL instructions and other patterns"""
    functions = []

    # Calculate the valid VRAM range for this code segment
    code_size = code_end_rom - code_start_rom
    vram_end = vram_start + code_size

    # Track JAL targets (these are definitely functions)
    jal_targets = set()

    # First pass: find all JAL targets
    offset = code_start_rom
    while offset < code_end_rom - 4:
        word = struct.unpack('>I', rom_data[offset:offset+4])[0]

        # JAL instruction: 0000 11xx xxxx xxxx xxxx xxxx xxxx xxxx
        if (word >> 26) == 0x03:  # JAL opcode
            target = (word & 0x03FFFFFF) << 2
            # Convert to full address (assuming same segment)
            target_vram = (vram_start & 0xF0000000) | target

            # IMPORTANT: Only include targets within our code segment
            # Skip RSP addresses (0x84xxxxxx), overlay addresses (0x801xxxxx higher), etc.
            if vram_start <= target_vram < vram_end:
                jal_targets.add(target_vram)

        offset += 4

    print(f"Found {len(jal_targets)} JAL targets within code segment")

    # Add known entry point
    jal_targets.add(vram_start)

    # Sort and create function list with sizes
    sorted_targets = sorted(jal_targets)

    for i, vram in enumerate(sorted_targets):
        # Calculate size (distance to next function)
        if i + 1 < len(sorted_targets):
            size = sorted_targets[i + 1] - vram
        else:
            # Last function - estimate size to end of code
            size = (vram_start + (code_end_rom - code_start_rom)) - vram

        # Ensure minimum size and reasonable maximum
        size = max(size, 0x10)
        size = min(size, 0x10000)  # Cap at 64KB per function

        functions.append({
            'vram': vram,
            'size': size,
            'name': f'func_{vram:08X}'
        })

    return functions

def generate_symbols_toml(functions: list, rom_start: int, vram_start: int, code_size: int) -> str:
    """Generate N64Recomp-compatible symbols.toml"""

    lines = [
        "# Auto-generated symbols file from ROM analysis",
        "# Generated by extract_functions.py using spimdisasm",
        "",
        "[[section]]",
        f'name = ".text"',
        f'rom = 0x{rom_start:08X}',
        f'vram = 0x{vram_start:08X}',
        f'size = 0x{code_size:X}',
        "",
        "functions = ["
    ]

    for i, func in enumerate(functions):
        comma = "," if i < len(functions) - 1 else ""
        lines.append(f'    {{ name = "{func["name"]}", vram = 0x{func["vram"]:08X}, size = 0x{func["size"]:X} }}{comma}')

    lines.append("]")

    return "\n".join(lines)

def main():
    rom_path = "rom/baserom.us.z64"
    output_path = "waverace-recomp/waverace.syms.toml"

    # Wave Race 64 code segment info
    CODE_START_ROM = 0x1000
    CODE_END_ROM = 0x8CDB0  # From splat analysis
    VRAM_START = 0x80046800

    print(f"Reading ROM: {rom_path}")
    rom_data = read_rom(rom_path)
    print(f"ROM size: {len(rom_data)} bytes")

    code_size = CODE_END_ROM - CODE_START_ROM
    print(f"Code segment: ROM 0x{CODE_START_ROM:X} - 0x{CODE_END_ROM:X} ({code_size} bytes)")
    print(f"VRAM: 0x{VRAM_START:08X}")

    print("\nAnalyzing code for function boundaries...")
    functions = detect_functions(rom_data, CODE_START_ROM, CODE_END_ROM, VRAM_START)
    print(f"Detected {len(functions)} functions")

    # Generate symbols.toml
    symbols_content = generate_symbols_toml(functions, CODE_START_ROM, VRAM_START, code_size)

    # Write output
    print(f"\nWriting symbols to: {output_path}")
    with open(output_path, 'w') as f:
        f.write(symbols_content)

    print("Done!")
    print(f"\nFirst 10 functions:")
    for func in functions[:10]:
        print(f"  {func['name']}: 0x{func['vram']:08X} size=0x{func['size']:X}")

if __name__ == "__main__":
    main()
