[[section]]
name = ".overlay_801E"
rom = 0x000A95E8
vram = 0x801E0000
size = 0x19168

functions = [
    { name = "ovl_func_801E0000", vram = 0x801E0000, size = 0x6C },
    { name = "ovl_func_801E006C", vram = 0x801E006C, size = 0xC0 },
    { name = "ovl_func_801E012C", vram = 0x801E012C, size = 0xF8 },
    { name = "ovl_func_801E0224", vram = 0x801E0224, size = 0xA8 },
    { name = "ovl_func_801E02CC", vram = 0x801E02CC, size = 0x1AC },
    { name = "ovl_func_801E0478", vram = 0x801E0478, size = 0x4C0 },
    { name = "ovl_func_801E0938", vram = 0x801E0938, size = 0x654 },
    { name = "ovl_func_801E0F8C", vram = 0x801E0F8C, size = 0x24 },
    { name = "ovl_func_801E0FB0", vram = 0x801E0FB0, size = 0x40 },
    { name = "ovl_func_801E0FF0", vram = 0x801E0FF0, size = 0x104 },
    { name = "ovl_func_801E10F4", vram = 0x801E10F4, size = 0xC0 },
    { name = "ovl_func_801E11B4", vram = 0x801E11B4, size = 0xDC },
    { name = "ovl_func_801E1290", vram = 0x801E1290, size = 0x2C },
    { name = "ovl_func_801E12BC", vram = 0x801E12BC, size = 0x190 },
    { name = "ovl_func_801E144C", vram = 0x801E144C, size = 0x1A4 },
    { name = "ovl_func_801E15F0", vram = 0x801E15F0, size = 0x64 },
    { name = "ovl_func_801E1654", vram = 0x801E1654, size = 0x554 },
    { name = "ovl_func_801E1BA8", vram = 0x801E1BA8, size = 0x1D4 },
    { name = "ovl_func_801E1D7C", vram = 0x801E1D7C, size = 0x110 },
    { name = "ovl_func_801E1E8C", vram = 0x801E1E8C, size = 0x1CC },
    { name = "ovl_func_801E2058", vram = 0x801E2058, size = 0x244 },
    { name = "ovl_func_801E229C", vram = 0x801E229C, size = 0x7C },
    { name = "ovl_func_801E2318", vram = 0x801E2318, size = 0x218 },
    { name = "ovl_func_801E2530", vram = 0x801E2530, size = 0x1DC },
    { name = "ovl_func_801E270C", vram = 0x801E270C, size = 0x198 },
    { name = "ovl_func_801E28A4", vram = 0x801E28A4, size = 0x1C8 },
    { name = "ovl_func_801E2A6C", vram = 0x801E2A6C, size = 0x9C },
    { name = "ovl_func_801E2B08", vram = 0x801E2B08, size = 0x84 },
    { name = "ovl_func_801E2B8C", vram = 0x801E2B8C, size = 0x88 },
    { name = "ovl_func_801E2C14", vram = 0x801E2C14, size = 0x27C },
    { name = "ovl_func_801E2E90", vram = 0x801E2E90, size = 0x9C },
    { name = "ovl_func_801E2F2C", vram = 0x801E2F2C, size = 0x274 },
    { name = "ovl_func_801E31A0", vram = 0x801E31A0, size = 0xB0 },
    { name = "ovl_func_801E3250", vram = 0x801E3250, size = 0x1C4 },
    { name = "ovl_func_801E3414", vram = 0x801E3414, size = 0xE4 },
    { name = "ovl_func_801E34F8", vram = 0x801E34F8, size = 0x64 },
    { name = "ovl_func_801E355C", vram = 0x801E355C, size = 0x13C },
    { name = "ovl_func_801E3698", vram = 0x801E3698, size = 0x44 },
    { name = "ovl_func_801E36DC", vram = 0x801E36DC, size = 0x474 },
    { name = "ovl_func_801E3B50", vram = 0x801E3B50, size = 0xF8 },
    { name = "ovl_func_801E3C48", vram = 0x801E3C48, size = 0x144 },
    { name = "ovl_func_801E3D8C", vram = 0x801E3D8C, size = 0x44 },
    { name = "ovl_func_801E3DD0", vram = 0x801E3DD0, size = 0x60 },
    { name = "ovl_func_801E3E30", vram = 0x801E3E30, size = 0x60 },
    { name = "ovl_func_801E3E90", vram = 0x801E3E90, size = 0x50 },
    { name = "ovl_func_801E3EE0", vram = 0x801E3EE0, size = 0x294 },
    { name = "ovl_func_801E4174", vram = 0x801E4174, size = 0x260 },
    { name = "ovl_func_801E43D4", vram = 0x801E43D4, size = 0x6C },
    { name = "ovl_func_801E4440", vram = 0x801E4440, size = 0x34C },
    { name = "ovl_func_801E478C", vram = 0x801E478C, size = 0x47C },
    { name = "ovl_func_801E4C08", vram = 0x801E4C08, size = 0x30 },
    { name = "ovl_func_801E4C38", vram = 0x801E4C38, size = 0x28 },
    { name = "ovl_func_801E4C60", vram = 0x801E4C60, size = 0x30 },
    { name = "ovl_func_801E4C90", vram = 0x801E4C90, size = 0x70 },
    { name = "ovl_func_801E4D00", vram = 0x801E4D00, size = 0x138 },
    { name = "ovl_func_801E4E38", vram = 0x801E4E38, size = 0x20 },
    { name = "ovl_func_801E4E58", vram = 0x801E4E58, size = 0x20 },
    { name = "ovl_func_801E4E78", vram = 0x801E4E78, size = 0x28 },
    { name = "ovl_func_801E4EA0", vram = 0x801E4EA0, size = 0x28 },
    { name = "ovl_func_801E4EC8", vram = 0x801E4EC8, size = 0xDC },
    { name = "ovl_func_801E4FA4", vram = 0x801E4FA4, size = 0x44 },
    { name = "ovl_func_801E4FE8", vram = 0x801E4FE8, size = 0x8 },
    { name = "ovl_func_801E4FF0", vram = 0x801E4FF0, size = 0x4C },
    { name = "ovl_func_801E503C", vram = 0x801E503C, size = 0x50 },
    { name = "ovl_func_801E508C", vram = 0x801E508C, size = 0x50 },
    { name = "ovl_func_801E50DC", vram = 0x801E50DC, size = 0x4C },
    { name = "ovl_func_801E5128", vram = 0x801E5128, size = 0x4C },
    { name = "ovl_func_801E5174", vram = 0x801E5174, size = 0x50 },
    { name = "ovl_func_801E51C4", vram = 0x801E51C4, size = 0x50 },
    { name = "ovl_func_801E5214", vram = 0x801E5214, size = 0x4C },
    { name = "ovl_func_801E5260", vram = 0x801E5260, size = 0x4C },
    { name = "ovl_func_801E52AC", vram = 0x801E52AC, size = 0x50 },
    { name = "ovl_func_801E52FC", vram = 0x801E52FC, size = 0x50 },
    { name = "ovl_func_801E534C", vram = 0x801E534C, size = 0x124 },
    { name = "ovl_func_801E5470", vram = 0x801E5470, size = 0x2C },
    { name = "ovl_func_801E549C", vram = 0x801E549C, size = 0xB8 },
    { name = "ovl_func_801E5554", vram = 0x801E5554, size = 0x98 },
    { name = "ovl_func_801E55EC", vram = 0x801E55EC, size = 0x154 },
    { name = "ovl_func_801E5740", vram = 0x801E5740, size = 0x154 },
    { name = "ovl_func_801E5894", vram = 0x801E5894, size = 0x1CC },
    { name = "ovl_func_801E5A60", vram = 0x801E5A60, size = 0x1D0 },
    { name = "ovl_func_801E5C30", vram = 0x801E5C30, size = 0x1D0 },
    { name = "ovl_func_801E5E00", vram = 0x801E5E00, size = 0x238 },
    { name = "ovl_func_801E6038", vram = 0x801E6038, size = 0x3C },
    { name = "ovl_func_801E6074", vram = 0x801E6074, size = 0x188 },
    { name = "ovl_func_801E61FC", vram = 0x801E61FC, size = 0xAC },
    { name = "ovl_func_801E62A8", vram = 0x801E62A8, size = 0x30 },
    { name = "ovl_func_801E62D8", vram = 0x801E62D8, size = 0x41C },
    { name = "ovl_func_801E66F4", vram = 0x801E66F4, size = 0x1F8 },
    { name = "ovl_func_801E68EC", vram = 0x801E68EC, size = 0x160 },
    { name = "ovl_func_801E6A4C", vram = 0x801E6A4C, size = 0x488 },
    { name = "ovl_func_801E6ED4", vram = 0x801E6ED4, size = 0x98 },
    { name = "ovl_func_801E6F6C", vram = 0x801E6F6C, size = 0x44 },
    { name = "ovl_func_801E6FB0", vram = 0x801E6FB0, size = 0xF0 },
    { name = "ovl_func_801E70A0", vram = 0x801E70A0, size = 0x108 },
    { name = "ovl_func_801E71A8", vram = 0x801E71A8, size = 0xD8 },
    { name = "ovl_func_801E7280", vram = 0x801E7280, size = 0x64 },
    { name = "ovl_func_801E72E4", vram = 0x801E72E4, size = 0xBC },
    { name = "ovl_func_801E73A0", vram = 0x801E73A0, size = 0x11C },
    { name = "ovl_func_801E74BC", vram = 0x801E74BC, size = 0xC8 },
    { name = "ovl_func_801E7584", vram = 0x801E7584, size = 0x13C },
    { name = "ovl_func_801E76C0", vram = 0x801E76C0, size = 0x248 },
    { name = "ovl_func_801E7908", vram = 0x801E7908, size = 0x31C },
    { name = "ovl_func_801E7C24", vram = 0x801E7C24, size = 0x34 },
    { name = "ovl_func_801E7C58", vram = 0x801E7C58, size = 0xC },
    { name = "ovl_func_801E7C64", vram = 0x801E7C64, size = 0x210 },
    { name = "ovl_func_801E7E74", vram = 0x801E7E74, size = 0x164 },
    { name = "ovl_func_801E7FD8", vram = 0x801E7FD8, size = 0xD8 },
    { name = "ovl_func_801E80B0", vram = 0x801E80B0, size = 0x1E8 },
    { name = "ovl_func_801E8298", vram = 0x801E8298, size = 0x2B4 },
    { name = "ovl_func_801E854C", vram = 0x801E854C, size = 0x64 },
    { name = "ovl_func_801E85B0", vram = 0x801E85B0, size = 0x130 },
    { name = "ovl_func_801E86E0", vram = 0x801E86E0, size = 0x120 },
    { name = "ovl_func_801E8800", vram = 0x801E8800, size = 0x324 },
    { name = "ovl_func_801E8B24", vram = 0x801E8B24, size = 0x404 },
    { name = "ovl_func_801E8F28", vram = 0x801E8F28, size = 0x3D4 },
    { name = "ovl_func_801E92FC", vram = 0x801E92FC, size = 0x170 },
    { name = "ovl_func_801E946C", vram = 0x801E946C, size = 0x28 },
    { name = "ovl_func_801E9494", vram = 0x801E9494, size = 0x3C4 },
    { name = "ovl_func_801E9858", vram = 0x801E9858, size = 0x2AC },
    { name = "ovl_func_801E9B04", vram = 0x801E9B04, size = 0x1B4 },
    { name = "ovl_func_801E9CB8", vram = 0x801E9CB8, size = 0xB4 },
    { name = "ovl_func_801E9D6C", vram = 0x801E9D6C, size = 0x2C4 },
    { name = "ovl_func_801EA030", vram = 0x801EA030, size = 0x80 },
    { name = "ovl_func_801EA0B0", vram = 0x801EA0B0, size = 0x33C },
    { name = "ovl_func_801EA3EC", vram = 0x801EA3EC, size = 0xCC },
    { name = "ovl_func_801EA4B8", vram = 0x801EA4B8, size = 0xE4 },
    { name = "ovl_func_801EA59C", vram = 0x801EA59C, size = 0x194 },
    { name = "ovl_func_801EA730", vram = 0x801EA730, size = 0x33C },
    { name = "ovl_func_801EAA6C", vram = 0x801EAA6C, size = 0x344 },
    { name = "ovl_func_801EADB0", vram = 0x801EADB0, size = 0x204 },
    { name = "ovl_func_801EAFB4", vram = 0x801EAFB4, size = 0x108 },
    { name = "ovl_func_801EB0BC", vram = 0x801EB0BC, size = 0xC4 },
    { name = "ovl_func_801EB180", vram = 0x801EB180, size = 0x170 },
    { name = "ovl_func_801EB2F0", vram = 0x801EB2F0, size = 0x44C },
    { name = "ovl_func_801EB73C", vram = 0x801EB73C, size = 0x1F8 },
    { name = "ovl_func_801EB934", vram = 0x801EB934, size = 0x160 },
    { name = "ovl_func_801EBA94", vram = 0x801EBA94, size = 0x768 },
    { name = "ovl_func_801EC1FC", vram = 0x801EC1FC, size = 0x10 },
    { name = "ovl_func_801EC20C", vram = 0x801EC20C, size = 0x2F4 },
    { name = "ovl_func_801EC500", vram = 0x801EC500, size = 0x208 },
    { name = "ovl_func_801EC708", vram = 0x801EC708, size = 0x128 },
    { name = "ovl_func_801EC830", vram = 0x801EC830, size = 0x128 },
    { name = "ovl_func_801EC958", vram = 0x801EC958, size = 0x19C },
    { name = "ovl_func_801ECAF4", vram = 0x801ECAF4, size = 0x1AC },
    { name = "ovl_func_801ECCA0", vram = 0x801ECCA0, size = 0x364 },
    { name = "ovl_func_801ED004", vram = 0x801ED004, size = 0x8C },
    { name = "ovl_func_801ED090", vram = 0x801ED090, size = 0x68 },
    { name = "ovl_func_801ED0F8", vram = 0x801ED0F8, size = 0x5C },
    { name = "ovl_func_801ED154", vram = 0x801ED154, size = 0x18C },
    { name = "ovl_func_801ED2E0", vram = 0x801ED2E0, size = 0x24 },
    { name = "ovl_func_801ED304", vram = 0x801ED304, size = 0x34 },
    { name = "ovl_func_801ED338", vram = 0x801ED338, size = 0x50 },
    { name = "ovl_func_801ED388", vram = 0x801ED388, size = 0x158 },
    { name = "ovl_func_801ED4E0", vram = 0x801ED4E0, size = 0xC8 },
    { name = "ovl_func_801ED5A8", vram = 0x801ED5A8, size = 0xEC },
    { name = "ovl_func_801ED694", vram = 0x801ED694, size = 0x1B4 },
    { name = "ovl_func_801ED848", vram = 0x801ED848, size = 0x34 },
    { name = "ovl_func_801ED87C", vram = 0x801ED87C, size = 0x250 },
    { name = "ovl_func_801EDACC", vram = 0x801EDACC, size = 0x14 },
    { name = "ovl_func_801EDAE0", vram = 0x801EDAE0, size = 0x8C },
    { name = "ovl_func_801EDB6C", vram = 0x801EDB6C, size = 0x68 },
    { name = "ovl_func_801EDBD4", vram = 0x801EDBD4, size = 0x8C },
    { name = "ovl_func_801EDC60", vram = 0x801EDC60, size = 0xA4 },
    { name = "ovl_func_801EDD04", vram = 0x801EDD04, size = 0x8C },
    { name = "ovl_func_801EDD90", vram = 0x801EDD90, size = 0x20C },
    { name = "ovl_func_801EDF9C", vram = 0x801EDF9C, size = 0x60 },
    { name = "ovl_func_801EDFFC", vram = 0x801EDFFC, size = 0x44 },
    { name = "ovl_func_801EE040", vram = 0x801EE040, size = 0x1E8 },
    { name = "ovl_func_801EE228", vram = 0x801EE228, size = 0x4C },
    { name = "ovl_func_801EE274", vram = 0x801EE274, size = 0xD0 },
    { name = "ovl_func_801EE344", vram = 0x801EE344, size = 0xB8 },
    { name = "ovl_func_801EE3FC", vram = 0x801EE3FC, size = 0x70 },
    { name = "ovl_func_801EE46C", vram = 0x801EE46C, size = 0x58 },
    { name = "ovl_func_801EE4C4", vram = 0x801EE4C4, size = 0xC },
    { name = "ovl_func_801EE4D0", vram = 0x801EE4D0, size = 0x224 },
    { name = "ovl_func_801EE6F4", vram = 0x801EE6F4, size = 0x1AC },
    { name = "ovl_func_801EE8A0", vram = 0x801EE8A0, size = 0x7C },
    { name = "ovl_func_801EE91C", vram = 0x801EE91C, size = 0x60 },
    { name = "ovl_func_801EE97C", vram = 0x801EE97C, size = 0x44 },
    { name = "ovl_func_801EE9C0", vram = 0x801EE9C0, size = 0x3B0 },
    { name = "ovl_func_801EED70", vram = 0x801EED70, size = 0x794 },
    { name = "ovl_func_801EF504", vram = 0x801EF504, size = 0xB50 },
    { name = "ovl_func_801F0054", vram = 0x801F0054, size = 0x22C },
    { name = "ovl_func_801F0280", vram = 0x801F0280, size = 0x160 },
    { name = "ovl_func_801F03E0", vram = 0x801F03E0, size = 0x16C },
    { name = "ovl_func_801F054C", vram = 0x801F054C, size = 0x480 },
    { name = "ovl_func_801F09CC", vram = 0x801F09CC, size = 0x40C },
    { name = "ovl_func_801F0DD8", vram = 0x801F0DD8, size = 0xA4 },
    { name = "ovl_func_801F0E7C", vram = 0x801F0E7C, size = 0x22C },
    { name = "ovl_func_801F10A8", vram = 0x801F10A8, size = 0xE0 },
    { name = "ovl_func_801F1188", vram = 0x801F1188, size = 0x154 },
    { name = "ovl_func_801F12DC", vram = 0x801F12DC, size = 0xC0 },
    { name = "ovl_func_801F139C", vram = 0x801F139C, size = 0x14C },
    { name = "ovl_func_801F14E8", vram = 0x801F14E8, size = 0xBC },
    { name = "ovl_func_801F15A4", vram = 0x801F15A4, size = 0xB4 },
    { name = "ovl_func_801F1658", vram = 0x801F1658, size = 0x9C },
    { name = "ovl_func_801F16F4", vram = 0x801F16F4, size = 0x90 },
    { name = "ovl_func_801F1784", vram = 0x801F1784, size = 0x94 },
    { name = "ovl_func_801F1818", vram = 0x801F1818, size = 0xEC },
    { name = "ovl_func_801F1904", vram = 0x801F1904, size = 0xD8 },
    { name = "ovl_func_801F19DC", vram = 0x801F19DC, size = 0xB4 },
    { name = "ovl_func_801F1A90", vram = 0x801F1A90, size = 0x100 },
    { name = "ovl_func_801F1B90", vram = 0x801F1B90, size = 0x16C },
    { name = "ovl_func_801F1CFC", vram = 0x801F1CFC, size = 0x40 },
    { name = "ovl_func_801F1D3C", vram = 0x801F1D3C, size = 0x1B8 },
    { name = "ovl_func_801F1EF4", vram = 0x801F1EF4, size = 0xE0 },
    { name = "ovl_func_801F1FD4", vram = 0x801F1FD4, size = 0x1CC },
    { name = "ovl_func_801F21A0", vram = 0x801F21A0, size = 0x188 },
    { name = "ovl_func_801F2328", vram = 0x801F2328, size = 0x78 },
    { name = "ovl_func_801F23A0", vram = 0x801F23A0, size = 0x2A0 },
    { name = "ovl_func_801F2640", vram = 0x801F2640, size = 0x44 },
    { name = "ovl_func_801F2684", vram = 0x801F2684, size = 0xC8 },
    { name = "ovl_func_801F274C", vram = 0x801F274C, size = 0x7C },
    { name = "ovl_func_801F27C8", vram = 0x801F27C8, size = 0x64 },
    { name = "ovl_func_801F282C", vram = 0x801F282C, size = 0x98 },
    { name = "ovl_func_801F28C4", vram = 0x801F28C4, size = 0x70 },
    { name = "ovl_func_801F2934", vram = 0x801F2934, size = 0x58 },
    { name = "ovl_func_801F298C", vram = 0x801F298C, size = 0x70 },
    { name = "ovl_func_801F29FC", vram = 0x801F29FC, size = 0x12C },
    { name = "ovl_func_801F2B28", vram = 0x801F2B28, size = 0xF4 },
    { name = "ovl_func_801F2C1C", vram = 0x801F2C1C, size = 0x430 },
    { name = "ovl_func_801F304C", vram = 0x801F304C, size = 0x40 },
    { name = "ovl_func_801F308C", vram = 0x801F308C, size = 0x1E4 },
    { name = "ovl_func_801F3270", vram = 0x801F3270, size = 0x50 },
    { name = "ovl_func_801F32C0", vram = 0x801F32C0, size = 0x1F4 },
    { name = "ovl_func_801F34B4", vram = 0x801F34B4, size = 0x64 },
    { name = "ovl_func_801F3518", vram = 0x801F3518, size = 0x1C8 },
    { name = "ovl_func_801F36E0", vram = 0x801F36E0, size = 0x5C },
    { name = "ovl_func_801F373C", vram = 0x801F373C, size = 0x1CC },
    { name = "ovl_func_801F3908", vram = 0x801F3908, size = 0xC4 },
    { name = "ovl_func_801F39CC", vram = 0x801F39CC, size = 0x3F8 },
    { name = "ovl_func_801F3DC4", vram = 0x801F3DC4, size = 0x648 },
    { name = "ovl_func_801F440C", vram = 0x801F440C, size = 0x140 },
    { name = "ovl_func_801F454C", vram = 0x801F454C, size = 0xAD4 },
    { name = "ovl_func_801F5020", vram = 0x801F5020, size = 0x410 },
    { name = "ovl_func_801F5430", vram = 0x801F5430, size = 0x2C4 },
    { name = "ovl_func_801F56F4", vram = 0x801F56F4, size = 0x7D0 },
    { name = "ovl_func_801F5EC4", vram = 0x801F5EC4, size = 0x644 },
    { name = "ovl_func_801F6508", vram = 0x801F6508, size = 0x83C },
    { name = "ovl_func_801F6D44", vram = 0x801F6D44, size = 0x364 },
    { name = "ovl_func_801F70A8", vram = 0x801F70A8, size = 0x340 },
    { name = "ovl_func_801F73E8", vram = 0x801F73E8, size = 0x240 },
    { name = "ovl_func_801F7628", vram = 0x801F7628, size = 0x17A8 },
    { name = "ovl_func_801F8DD0", vram = 0x801F8DD0, size = 0x398 },
]